CREATE TABLE USERS (
    ID NUMBER(10) PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL
);

CREATE TABLE TASKS (
    ID NUMBER(10) PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(255),
    STATUS VARCHAR2(50),
    PRIORITY VARCHAR2(50),
    DUE_DATE DATE,
    CREATED_AT DATE,
    UPDATED_AT DATE,
    USER_ID NUMBER(10),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
